name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps: 
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      working-directory: ./TeaMan
      run: |
        nuget sources add -name "private-packages" -Source https://nuget.pkg.github.com/yanjingzhu/index.json -StorePasswordInClearText -Username yanjingzhu -Password ${env:Password}
        dotnet restore
      env:
        Password: ${{ secrets.PackagePAT }}
    - name: Build
      working-directory: ./TeaMan
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./TeaMan
      run: dotnet test --no-build --verbosity normal
